<?php

namespace AppBundle\Repository;

/**
 * EmployerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployerRepository extends \Doctrine\ORM\EntityRepository
{
}
