<?php

namespace AppBundle\Repository;

/**
 * SystemUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SystemUserRepository extends \Doctrine\ORM\EntityRepository
{
}
